defmodule Atividade0903.Repo.Migrations.AddAlunosResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:alunos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :ra, :text, null: false
      add :age, :bigint, null: false
      add :period, :bigint, null: false
    end
  end

  def down do
    drop table(:alunos)
  end
end
